### ISSUE TITLE
👷 [CI] CI/CD 파이프라인 구축

### ISSUE THREAD

**Issue by hosung-222** [UMC-Matching-Center/U.M.C_Server#2]
## Description
깃허브 액션을 이용한 CI/CD 파이프라인 구축 

## To-do
- [x] Github Actions 스크립트 작성하기
- [x] ebextensions 작성
- [x] Elastic Beanstalk 생성
- [x] 기타 필요한 파일 작성
- [x] Health 체크용 API 구현
