### ISSUE TITLE
♻️ [refactor]로그인/회원가입 리팩토링

### ISSUE THREAD

**Issue by zzansol** [UMC-Matching-Center/U.M.C_Server#22]
## Description
설명을 작성하세요

## To-do
- [x] 회원가입 validation 추가
- [x] 회원가입시 학교 생성 로직 추가
- [x] 회원 상태, 회원 권한 생성 로직 추가
- [x] refresh 토큰 레디스 저장 로직 추가
- [x] jwt 예외처리
- [x] 컨트롤러 파라미터 수정
- [x] 닉네임 중복 확인 api 추가
