### ISSUE TITLE
✨ [feat] 일반 유저 홈 화면 API 구현

### ISSUE THREAD

**Issue by nahy-512** [UMC-Matching-Center/U.M.C_Server#25]
## Description
일반 유저 홈 화면 API 구현

## To-do
- [x] 프로젝트 리스트 조회
  - [x] 현재 매칭중인 프로젝트와 OB 프로젝트 구분
  - [x] 현재 매칭중이라면 모집 현황 표시하기
- [x] 프로젝트 상세 보기
- [x] 예외 처리
- [x] 테스트
