### ISSUE TITLE
✨ [feat] 챌린저 관리 구현 API

### ISSUE THREAD

**Issue by hosung-222** [UMC-Matching-Center/U.M.C_Server#31]
## Description
챌린저 관리 API 구현

## To-do
- [x] 현재 챌린저 조회 API
  - [x] 미지원, 지원완료, 결과 대기중, 매칭 완료 별 조회 기능
- [x] 챌린저의 차수 별 지원 팀 조회 API
- [x] 탈부 처리 API
- [x] 회원가입 대기 챌린저 관리
  - [X] 회원가입 대기 챌린저 조회 API
  - [x] 수락 API
  - [x] 거절 API
